/** @type {import('tailwindcss').Config} */
const withOpacity = (variable) => `rgb(var(${variable}) / <alpha-value>)`;

export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary:                  withOpacity('--color-primary'),
        'primary-container':      withOpacity('--color-primary-container'),
        'on-primary':             withOpacity('--color-on-primary'),
        'on-primary-container':   withOpacity('--color-on-primary-container'),
        secondary:                withOpacity('--color-secondary'),
        'secondary-container':    withOpacity('--color-secondary-container'),
        'on-secondary':           withOpacity('--color-on-secondary'),
        'on-secondary-container': withOpacity('--color-on-secondary-container'),
        tertiary:                 withOpacity('--color-tertiary'),
        'tertiary-container':     withOpacity('--color-tertiary-container'),
        'on-tertiary':            withOpacity('--color-on-tertiary'),
        error:                    withOpacity('--color-error'),
        'error-container':        withOpacity('--color-error-container'),
        surface:                  withOpacity('--color-surface'),
        'surface-dim':            withOpacity('--color-surface-dim'),
        'surface-bright':         withOpacity('--color-surface-bright'),
        'surface-container':      withOpacity('--color-surface-container'),
        'surface-container-low':  withOpacity('--color-surface-container-low'),
        'surface-container-high': withOpacity('--color-surface-container-high'),
        'surface-container-highest': withOpacity('--color-surface-container-highest'),
        'surface-variant':        withOpacity('--color-surface-variant'),
        'on-surface':             withOpacity('--color-on-surface'),
        'on-surface-variant':     withOpacity('--color-on-surface-variant'),
        background:               withOpacity('--color-background'),
        'on-background':          withOpacity('--color-on-background'),
        outline:                  withOpacity('--color-outline'),
        'outline-variant':        withOpacity('--color-outline-variant'),
        'inverse-surface':        withOpacity('--color-inverse-surface'),
        'inverse-on-surface':     withOpacity('--color-inverse-on-surface'),
        'inverse-primary':        withOpacity('--color-inverse-primary'),
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        body:    ['Plus Jakarta Sans', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
