/** @type {import('tailwindcss').Config} */
const withOpacity = (variable) => `rgb(var(${variable}) / <alpha-value>)`;

export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      // Viewports too short for the sign-in page's roomy spacing (most laptops)
      screens: {
        short: { raw: '(max-height: 760px)' },
      },
      colors: {
        primary:                  withOpacity('--color-primary'),
        'primary-container':      withOpacity('--color-primary-container'),
        'on-primary':             withOpacity('--color-on-primary'),
        'on-primary-container':   withOpacity('--color-on-primary-container'),
        secondary:                withOpacity('--color-secondary'),
        'secondary-container':    withOpacity('--color-secondary-container'),
        'on-secondary':           withOpacity('--color-on-secondary'),
        'on-secondary-container': withOpacity('--color-on-secondary-container'),
        tertiary:                 withOpacity('--color-tertiary'),
        'tertiary-container':     withOpacity('--color-tertiary-container'),
        'on-tertiary':            withOpacity('--color-on-tertiary'),
        error:                    withOpacity('--color-error'),
        'error-container':        withOpacity('--color-error-container'),
        surface:                  withOpacity('--color-surface'),
        'surface-dim':            withOpacity('--color-surface-dim'),
        'surface-bright':         withOpacity('--color-surface-bright'),
        'surface-container':      withOpacity('--color-surface-container'),
        'surface-container-low':  withOpacity('--color-surface-container-low'),
        'surface-container-high': withOpacity('--color-surface-container-high'),
        'surface-container-highest': withOpacity('--color-surface-container-highest'),
        'surface-variant':        withOpacity('--color-surface-variant'),
        'on-surface':             withOpacity('--color-on-surface'),
        'on-surface-variant':     withOpacity('--color-on-surface-variant'),
        background:               withOpacity('--color-background'),
        'on-background':          withOpacity('--color-on-background'),
        outline:                  withOpacity('--color-outline'),
        'outline-variant':        withOpacity('--color-outline-variant'),
        'inverse-surface':        withOpacity('--color-inverse-surface'),
        'inverse-on-surface':     withOpacity('--color-inverse-on-surface'),
        'inverse-primary':        withOpacity('--color-inverse-primary'),
        // Brand palette — defined on .qp-ui in index.css
        qp: {
          bg:          'var(--qp-bg)',
          panel:       'var(--qp-panel)',
          card:        'var(--qp-card)',
          ink:         'var(--qp-ink)',
          muted:       'var(--qp-muted)',
          line:        'var(--qp-line)',
          field:       'var(--qp-field)',
          fieldline:   'var(--qp-fieldline)',
          bar:         'var(--qp-bar)',
          track:       'var(--qp-track)',
          error:       'var(--qp-error)',
          errbg:       'var(--qp-errbg)',
          accent:      'var(--qp-accent)',
          'accent-fg': 'var(--qp-accent-fg)',
          'accent-ink':'var(--qp-accent-ink)',
        },
      },
      fontFamily: {
        display: ['Space Grotesk', 'sans-serif'],
        body:    ['Plus Jakarta Sans', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
        brand:        ['Hanken Grotesk', 'sans-serif'],
        'brand-mono': ['Space Mono', 'monospace'],
      },
      keyframes: {
        'qp-in':    { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'none' } },
        'qp-roll':  { from: { opacity: '0', transform: 'translateY(.28em)' }, to: { opacity: '1', transform: 'none' } },
        'qp-pulse': { '0%, 100%': { opacity: '1' }, '50%': { opacity: '.3' } },
        'qp-plus':  {
          '0%':   { opacity: '0', transform: 'translateY(3px)' },
          '15%':  { opacity: '1', transform: 'none' },
          '75%':  { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'qp-shake': {
          '0%, 100%': { transform: 'none' },
          '25%': { transform: 'translateX(-4px)' },
          '50%': { transform: 'translateX(3px)' },
          '75%': { transform: 'translateX(-2px)' },
        },
      },
      animation: {
        'qp-in':    'qp-in .8s cubic-bezier(.2,.7,.2,1) both',
        'qp-roll':  'qp-roll .55s cubic-bezier(.2,.8,.2,1) both',
        'qp-pulse': 'qp-pulse 2.4s ease-in-out infinite',
        'qp-plus':  'qp-plus 1.6s ease forwards',
        'qp-shake': 'qp-shake .4s ease',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
