/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary:                  '#cdbdff',
        'primary-container':      '#7c4dff',
        'on-primary':             '#370096',
        'on-primary-container':   '#fcf6ff',
        secondary:                '#44ddc1',
        'secondary-container':    '#00bea4',
        'on-secondary':           '#00382f',
        'on-secondary-container': '#00463b',
        tertiary:                 '#bdc2ff',
        'tertiary-container':     '#616ac5',
        'on-tertiary':            '#1b247f',
        error:                    '#ffb4ab',
        'error-container':        '#93000a',
        surface:                  '#131313',
        'surface-dim':            '#131313',
        'surface-bright':         '#393939',
        'surface-container':      '#201f1f',
        'surface-container-low':  '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'surface-variant':        '#353534',
        'on-surface':             '#e5e2e1',
        'on-surface-variant':     '#cac3d8',
        background:               '#131313',
        'on-background':          '#e5e2e1',
        outline:                  '#948ea1',
        'outline-variant':        '#494455',
        'inverse-surface':        '#e5e2e1',
        'inverse-on-surface':     '#313030',
        'inverse-primary':        '#6833ea',
      },
      fontFamily: {
        display: ['Hanken Grotesk', 'sans-serif'],
        body:    ['Inter', 'sans-serif'],
        mono:    ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
